# mod
mod_id=advcreation
mod_name=AdvancedCreation
mod_version=1.12.2-beta1.2.3
mod_author=ChryonicWolf(GraphiteGames)
mod_group=com.deadtiger.advcreation
mod_description=A mod that gives you an isometric perspective of minecraft and equips you with many simple tools to build with less effort and more fun
mixin_loader_class=com.deadtiger.advcreation.plugin.AdvCreationCorePlugin

# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=false

# minecraft
minecraft_version=1.12.2

# forge
forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12
fancy_gradle_version=1.1.+

# mixin
mixin_gradle_version=0.7.+
mixin_version=0.8.7
mixin_extras_version=0.5.0

#dependencies
fermiumbooter_version=968474:7279112
llibrary_version=243298:2504999
bewitchment_version=285439:6379256