pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.minecraftforge.net' }
        maven { url = 'https://repo.spongepowered.org/maven' }
        maven { url 'https://maven.gofancy.wtf/releases' }
        maven { url ='http://127.0.0.1:5000/forgeLibs' }
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.toString() == 'org.spongepowered.mixin') {
                useModule("org.spongepowered:mixingradle:${requested.version}")
            }
        }
    }
}